# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f2b7e6222ddb69036c094a9b2996581"
application_url = "https://appeared-association-accountability-observation.trycloudflare.com"
embedded = true
name = "vpr-app"
handle = "vpr-app-2"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://appeared-association-accountability-observation.trycloudflare.com/auth/callback",
  "https://appeared-association-accountability-observation.trycloudflare.com/auth/shopify/callback",
  "https://appeared-association-accountability-observation.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
