# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "da6f648adf9c9f804911ecea6f98307c"
application_url = "https://highlights-film-enjoy-hawaiian.trycloudflare.com"
embedded = true
name = "vpr-app"
handle = "vpr-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://highlights-film-enjoy-hawaiian.trycloudflare.com/auth/callback",
  "https://highlights-film-enjoy-hawaiian.trycloudflare.com/auth/shopify/callback",
  "https://highlights-film-enjoy-hawaiian.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
